using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.Extensions.DependencyInjection;
using NetEase.Models;
using NetEase.Services;
using NetEase.Views;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;

namespace NetEase.ViewModels
{
    public partial class MainViewModel : BaseViewModel
    {
        private readonly PlaylistService _playlistService;

        [ObservableProperty]
        private BaseViewModel _currentView;

        [ObservableProperty]
        private bool _isOverlayVisible;

        [ObservableProperty]
        private bool _isLeftSidebarExpanded = true;

        [ObservableProperty]
        private Playlist _selectedPlaylist;

        public TitleBarViewModel TitleBarVM { get; }
        public PlayerControlViewModel PlayerControlVM { get; }
        public AuthenticationViewModel AuthVM { get; }

        public ObservableCollection<Playlist> FavoritePlaylists { get; } = new();
        public ObservableCollection<NavigationItem> MainNavigationItems { get; }
        public ObservableCollection<NavigationItem> MyMusicNavigationItems { get; }
        public ObservableCollection<NavigationItem> MoreNavigationItems { get; }

        public MainViewModel(TitleBarViewModel titleBarVM, PlayerControlViewModel playerControlVM, AuthenticationViewModel authVM, PlaylistService playlistService)
        {
            TitleBarVM = titleBarVM;
            PlayerControlVM = playerControlVM;
            AuthVM = authVM;
            _playlistService = playlistService;

            MainNavigationItems = new ObservableCollection<NavigationItem>
            {
                new NavigationItem { DisplayName = "推荐", Icon = "\uE896", ViewModelType = typeof(LocalMusicViewModel) },
                new NavigationItem { DisplayName = "精选", Icon = "\uE8F1" , ViewModelType = typeof(FeaturedViewModel)},
                new NavigationItem { DisplayName = "播客", Icon = "\uE1D6", ViewModelType = typeof(PodcastViewModel) },
                new NavigationItem { DisplayName = "漫游", Icon = "\uE8DD", ViewModelType = typeof(PodcastViewModel) },
                new NavigationItem { DisplayName = "关注", Icon = "\uE77B", ViewModelType = typeof(FriendsViewModel) }
            };

            MyMusicNavigationItems = new ObservableCollection<NavigationItem>
            {
                new NavigationItem { DisplayName = "我喜欢的音乐", Icon = "\uE00B", ViewModelType = typeof(MyFavoriteMusicViewModel) },
                new NavigationItem { DisplayName = "最近播放", Icon = "\uE823" , ViewModelType = typeof(LocalMusicViewModel)},
                new NavigationItem { DisplayName = "本地音乐", Icon = "\uE1D6" , ViewModelType = typeof(LocalMusicViewModel)},
            };

            MoreNavigationItems = new ObservableCollection<NavigationItem>
            {
                new NavigationItem { DisplayName = "我的收藏", Icon = "\uE1DE", ViewModelType = typeof(LocalMusicViewModel) },
                new NavigationItem { DisplayName = "云盘", Icon = "\uE713", ViewModelType = typeof(LocalMusicViewModel)  },
                new NavigationItem { DisplayName = "已购", Icon = "\uE779", ViewModelType = typeof(LocalMusicViewModel)  }
            };

            InitializeAsync();
        }

        #region Commands (Generated by [RelayCommand])

        [RelayCommand]
        private void ToggleLeftSidebar()
        {
            IsLeftSidebarExpanded = !IsLeftSidebarExpanded;
        }

        [RelayCommand]
        private void ShowSignUp()
        {
            IsOverlayVisible = true;
        }

        [RelayCommand]
        private void HideOverlay()
        {
            IsOverlayVisible = false;
        }

        [RelayCommand]
        private async Task CreatePlaylistAsync()
        {
            var dialogVM = new InputDialogViewModel
            {
                Title = "创建新歌单",
                Message = "请输入新歌单的名称："
            };

            var dialogView = new InputDialogView
            {
                DataContext = dialogVM,
                Owner = Application.Current.MainWindow
            };

            var dialogResult = dialogView.ShowDialog();

            if (dialogResult == true && !string.IsNullOrWhiteSpace(dialogVM.InputText))
            {
                var newPlaylistDto = await _playlistService.CreatePlaylistAsync(dialogVM.InputText);
                if (newPlaylistDto != null)
                {
                    var newPlaylist = new Playlist
                    {
                        Id = newPlaylistDto.Id,
                        Title = newPlaylistDto.Name,
                        CoverImageUrl = newPlaylistDto.CoverImageUrl
                    };
                    FavoritePlaylists.Add(newPlaylist);
                }
            }
        }

        // Renamed from NavigateTo so the generator creates "NavigateCommand"
        [RelayCommand]
        private void Navigate(NavigationItem item)
        {
            if (item == null || item.ViewModelType == null) return;
            ClearAllSelections();
            item.IsSelected = true;
            CurrentView = (BaseViewModel)App.ServiceProvider.GetRequiredService(item.ViewModelType);
        }

        // Renamed from NavigateToPlaylist and logic merged from NavigateToPlaylistAsync
        [RelayCommand]
        private async Task NavigatePlaylist(Playlist playlist)
        {
            if (playlist == null) return;
            ClearAllSelections();
            playlist.IsSelected = true;
            var favoriteVm = App.ServiceProvider.GetRequiredService<MyFavoriteMusicViewModel>();
            await favoriteVm.LoadPlaylistAsync(playlist.Id);
            CurrentView = favoriteVm;
        }

        #endregion

        #region Private Methods

        private async void InitializeAsync()
        {
            var playlistDtos = await _playlistService.GetMyPlaylistsAsync();
            if (playlistDtos != null)
            {
                FavoritePlaylists.Clear();
                foreach (var dto in playlistDtos)
                {
                    FavoritePlaylists.Add(new Playlist
                    {
                        Id = dto.Id,
                        Title = dto.Name,
                        CoverImageUrl = dto.CoverImageUrl
                    });
                }
            }

            var favoriteNavItem = MyMusicNavigationItems.FirstOrDefault(item => item.ViewModelType == typeof(MyFavoriteMusicViewModel));
            if (favoriteNavItem != null)
            {
                Navigate(favoriteNavItem); // Now calls the new command method

                var favPlaylist = FavoritePlaylists.FirstOrDefault(p => p.Title == "我喜欢的音乐");
                if (CurrentView is MyFavoriteMusicViewModel vm && favPlaylist != null)
                {
                    await vm.LoadPlaylistAsync(favPlaylist.Id);
                }
            }
            else
            {
                Navigate(MainNavigationItems.FirstOrDefault());
            }
        }

        private void ClearAllSelections()
        {
            Debug.WriteLine("enter ClearAllSelections()");
            foreach (var navItem in MainNavigationItems.Concat(MyMusicNavigationItems).Concat(MoreNavigationItems))
            {
                navItem.IsSelected = false;
            }
            foreach (var playlist in FavoritePlaylists)
            {
                playlist.IsSelected = false;
            }
        }

        // Unused methods can be removed if NavigatePlaylist logic is fully merged
        // private void NavigateToFavorite() { ... }
        // private void LoadInitialDataAsync() { ... }
        // private void InitializeView() { ... }

        #endregion
    }
}